---
abstract: 'Dist::Zilla plugin that compiles Local::Msgfmt .po files to .mo files'
author:
  - 'Patrick Donelan <pat@patspam.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.100922'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-LocaleMsgfmt
recommends: {}
requires:
  Dist::Zilla::Role::BeforeBuild: 0
  Locale::Msgfmt: 0.14
  Moose: 0
resources:
  repository: http://github.com/pdonelan/Dist-Zilla-Plugin-LocaleMsgfmt
version: 1.100970
